### ISSUE TITLE
9.4 compatibility problem?

### ISSUE THREAD

**Issue by csawyerYumaed** [marcmunro/veil#1]
$ pg_config | grep VERSION
VERSION = PostgreSQL 9.4.5
$ make
GNUmakefile:102: warning: overriding recipe for target 'clean'
/usr/lib/postgresql/9.4/lib/pgxs/src/makefiles/pgxs.mk:223: warning: ignoring old recipe for target 'clean'
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -fpic -O0  -I. -I./ -I/usr/include/postgresql/9.4/server -I/usr/include/postgresql/internal -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.6  -c -o src/veil_shmem.o src/veil_shmem.c
src/veil_shmem.c:85:1: error: initializer element is not constant
 static LWLockId  VeilLWLock = AddinShmemInitLock;
 ^
src/veil_shmem.c:91:1: error: initializer element is not constant
 static LWLockId  InitialLWLock = AddinShmemInitLock;
 ^
<builtin>: recipe for target 'src/veil_shmem.o' failed
make: **\* [src/veil_shmem.o] Error 1

**Comment by marcmunro** [comment]
Yep, I hadn't updated veil for some time.

All should now be well.  

I have updated the git repos and released a new tarball (with docs) to pgfoundry.  Sadly I am unable to update the docs on pgfoundry due to permission problems - it is currently unclear what the future holds for pgfoundry, so I am not bugging anyone about it.
